# Generated by Django 4.2.8 on 2024-04-05 21:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("test11", "0006_rename_side_effects_product_side_effects_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CallbackRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Имя")),
                ("phone", models.CharField(max_length=20, verbose_name="Телефон")),
                (
                    "call_now",
                    models.BooleanField(default=False, verbose_name="Позвонить сейчас"),
                ),
                (
                    "call_time",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("10-12", "с 10:00 до 12:00"),
                            ("12-14", "с 12:00 до 14:00"),
                            ("14-16", "с 14:00 до 16:00"),
                            ("16-18", "с 16:00 до 18:00"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="Время звонка",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата запроса"
                    ),
                ),
            ],
        ),
    ]
