# Generated by Django 4.2.8 on 2024-04-07 17:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("test11", "0008_callbackrequest_accept_policy"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="callbackrequest",
            options={
                "verbose_name": "Заказ звонка",
                "verbose_name_plural": "Обратная связь",
            },
        ),
        migrations.RemoveField(
            model_name="callbackrequest",
            name="accept_policy",
        ),
    ]
