# Generated by Django 4.2.8 on 2024-02-24 21:58

from django.db import migrations, models
import sitecatalog.models


class Migration(migrations.Migration):

    dependencies = [
        ('sitecatalog', '0002_alter_product_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to=sitecatalog.models.get_image_filename1, verbose_name='Изображение'),
        ),
    ]
