# Generated by Django 4.2.8 on 2024-04-04 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitecatalog', '0003_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='release_form',
            field=models.TextField(blank=True, verbose_name='Форма выпуска'),
        ),
    ]
